name: Laravel

on: pull_request

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    container: owow/laravel-php:8.1

    steps:
    - uses: actions/checkout@v3

    - name: Composer
      run: composer install --no-scripts --prefer-dist --ignore-platform-reqs

    - name: Cache composer dependencies
      uses: actions/cache@v3
      with:
        path: vendor
        key: composer-${{ hashFiles('composer.lock') }}

    - name: Phpunit
      run: vendor/bin/phpunit
